module.exports = {
  globals: {
    'ts-jest': {
      tsconfig: '<rootDir>/tsconfig.test.json',
    },
  },
  roots:     ['<rootDir>/src'],
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': 'ts-jest',
  },
  modulePaths:             ['src'],
  testEnvironment:         'jest-environment-jsdom',
  moduleNameMapper:        {
    '\\.(css|less|scss|sss|styl)$':                                 'identity-obj-proxy',
    'react-teleporter':                                             '<rootDir>/../../test/react-teleporter.js',
    '\\.(jpg|jpeg|png|gif|webp|svg|mp4|webm|wav|mp3|m4a|aac|oga)$': '<rootDir>/../../test/imageMock.js',
    '^@utils(.*)$':                                                 '<rootDir>/src/utils/$1',
    '^@definitions(.*)$':                                           '<rootDir>/src/definitions/index.ts',
    '^@constants(.*)$':                                             '<rootDir>/src/constants/$1',
    '^@redux/(.*)$':                                                '<rootDir>/src/redux/$1',
    '^@ducks(.*)$':                                                 '<rootDir>/src/redux/ducks/$1',
    '^./__mocks__(.*)$':                                            '<rootDir>/src/__mocks__/$1',
    '^@components(.*)$':                                            '<rootDir>/src/components/$1',
    '^@containers(.*)$':                                            '<rootDir>/src/containers/$1',
    '^@mocks(.*)$':                                                 '<rootDir>/src/mocks/$1',
    '^@hooks(.*)$':                                                 '<rootDir>/src/hooks/$1',
    '^@test/(.*)$':                                                 '<rootDir>/src/test/$1',
    '^@images(.*)$':                                                '<rootDir>/src/assets/images/$1',
    '^@features(.*)$':                                              '<rootDir>/src/features/$1',
    '^@helpers(.*)$':                                               '<rootDir>/src/helpers/$1',
  },
//   setupFilesAfterEnv:   ['jest-canvas-mock', '../../test/setupTests.ts'],
  moduleDirectories:    ['node_modules', __dirname],
  testRegex:            '(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  collectCoverage:      true,
  coverageDirectory:    '<rootDir>/coverage',
};
